modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"
[[mods]]
modId="flowerpots"
version="${file.jarVersion}"
displayName="Artemis' Flower Pots"
authors="Artemis"
description='''
This mod adds lots of new and improved flower pots
'''
[[dependencies.flowerpots]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.flowerpots]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="BOTH"
